services:
  - type: web
    name: amul-stock-backend
    runtime: node
    plan: free

    buildCommand: |
      npm install
      npx playwright install chromium

    startCommand: npm start

    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0